fixed build scripts

diff --git a/tools/setup-environment b/tools/setup-environment
--- a/tools/setup-environment
+++ b/tools/setup-environment
@@ -2,38 +2,92 @@
 #
 
 CWD=`pwd`
+PROGNAME="setup-environment"
+PACKAGE_CLASSES=${PACKAGE_CLASSES:-package_rpm}
+
+
+usage()
+{
+    echo -e "
+Usage: MACHINE=<machine> DISTRO=<distro> source $PROGNAME <build-dir>
+Usage:                                   source $PROGNAME <build-dir>
+    <machine>    machine name
+    <distro>     distro name
+    <build-dir>  build directory
+
+The first usage is for creating a new build directory. In this case, the
+script creates the build directory <build-dir>, configures it for the
+specified <machine> and <distro>, and prepares the calling shell for running
+bitbake on the build directory.
+
+The second usage is for using an existing build directory. In this case,
+the script prepares the calling shell for running bitbake on the build
+directory <build-dir>. The build directory configuration is unchanged.
+"
+}
+
+clean_up()
+{
+   unset EULA LIST_MACHINES VALID_MACHINE
+   unset CWD TEMPLATES SHORTOPTS LONGOPTS ARGS PROGNAME
+   unset generated_config updated
+   unset MACHINE SDKMACHINE DISTRO OEROOT
+}
 
 # get command line options
-OLD_OPTIND=$OPTIND
-unset FSLDISTRO
+SHORTOPTS="h"
+LONGOPTS="help"
 
-while getopts "k:r:t:b:e:gh" fsl_setup_flag
+ARGS=$(getopt --options $SHORTOPTS  \
+  --longoptions $LONGOPTS --name $PROGNAME -- "$@" )
+# Print the usage menu if invalid options are specified
+if [ $? != 0 -o $# -lt 1 ]; then
+   usage && clean_up
+   return 1
+fi
+
+eval set -- "$ARGS"
+while true;
 do
-    case $fsl_setup_flag in
-        b) BUILD_DIR="$OPTARG";
-           echo -e "\nBuild directory is " $BUILD_DIR
+    case $1 in
+        -h|--help)
+           usage
+           clean_up
+           return 0
            ;;
-        h) fsl_setup_help='true';
-           ;;
-        \?) fsl_setup_error='true';
+        --)
+           shift
+           break
            ;;
     esac
 done
-shift $((OPTIND-1))
-if [ $# -ne 0 ]; then
-    fsl_setup_error=true
-    echo -e "Invalid command line ending: '$@'"
-fi
-OPTIND=$OLD_OPTIND
-if test $fsl_setup_help; then
-    usage && clean_up && return 1
-elif test $fsl_setup_error; then
-    clean_up && return 1
-fi
-
 
 if [ "$(whoami)" = "root" ]; then
     echo "ERROR: do not use the BSP as root. Exiting..."
+fi
+
+if [ ! -e $1/conf/local.conf.sample ]; then
+    build_dir_setup_enabled="true"
+else
+    build_dir_setup_enabled="false"
+fi
+
+if [ "$build_dir_setup_enabled" = "true" ] && [ -z "$MACHINE" ]; then
+    usage
+    echo -e "ERROR: You must set MACHINE when creating a new build directory."
+    clean_up
+    return 1
+fi
+
+if [ -z "$SDKMACHINE" ]; then
+    SDKMACHINE='i686'
+fi
+
+if [ "$build_dir_setup_enabled" = "true" ] && [ -z "$DISTRO" ]; then
+    usage
+    echo -e "ERROR: You must set DISTRO when creating a new build directory."
+    clean_up
+    return 1
 fi
 
 OEROOT=$PWD/sources/poky
@@ -51,7 +105,6 @@ fi
 # Clean up PATH, because if it includes tokens to current directories somehow,
 # wrong binaries can be used instead of the expected ones during task execution
 export PATH="`echo $PATH | sed 's/\(:.\|:\)*:/:/g;s/^.\?://;s/:.\?$//'`"
-
 
 cat <<EOF
 
@@ -74,4 +127,3 @@ Common targets are:
 EOF
 
 clean_up
-unset FSLDISTRO
